name: fson
description: File Sharing Over Network.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.10
  mobx: ^2.1.4
  flutter_mobx: ^2.0.6+5
  dio: ^5.0.0
  slang: ^3.12.0
  slang_flutter: ^3.12.0
  auto_route: ^5.0.4
  flutter_dotenv: ^5.0.2
  shared_preferences: ^2.0.20
  flutter_dropzone_web: ^3.0.8
  flutter_dropzone: ^3.0.5
  restart_app: ^1.1.2

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.3.3
  slang_build_runner: ^3.12.0
  auto_route_generator: ^5.0.3
  mobx_codegen: ^2.1.1

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
# assets:
#   - .env
